jobs:
  slashCommandDispatch:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v3
      with:
        commands: 'spotlessApply

          generateLicenses'
        issue-type: pull-request
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
name: Slash Command Dispatch
on:
  repository_dispatch:
    types: trigger-ga___ChatOps.yml
permissions: write-all
