jobs:
  validate-pr:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: neo4j/github-action-traceability@v1
      with:
        github_api_token: ${{ secrets.GITHUB_TOKEN }}
        global_verification_strategy: commits_and_pr_title
        short_link_verification_strategy: trello_or_noid
        trello_api_key: ${{ secrets.TRELLO_API_KEY }}
        trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
name: traceability
on:
  repository_dispatch:
    types: trigger-ga___traceability.yaml
